name: "Generate usage"
description: "Generate usage"
inputs:
  dbHost:
    description: "Databricks host"
    required: true
  dbSqlWarehouseId:
    description: "Databricks SQL warehouse ID"
    required: true

runs:
    using: composite
    steps:
      - name: Test terraform output
        shell: bash
        run: terraform output
        working-directory: .infra/personas

      - name: Debugging
        shell: bash
        run: jq -s 'add' <(cd .infra/personas; terraform output -json) <(cd .infra/infra; terraform output -json)

      - name: Generate usage
        shell: bash
        run: make gen-test-usage
        env:
          dbHost: ${{ inputs.dbHost }}
          dbWarehouseId: ${{ inputs.dbSqlWarehouseId }}