// Code generated by mockery v2.53.3. DO NOT EDIT.

package databricks

import (
	context "context"

	iam "github.com/databricks/databricks-sdk-go/service/iam"
	mock "github.com/stretchr/testify/mock"

	repo "cli-plugin-databricks/databricks/repo"

	types "cli-plugin-databricks/databricks/repo/types"
)

// mockIdentityStoreAccountRepository is an autogenerated mock type for the identityStoreAccountRepository type
type mockIdentityStoreAccountRepository struct {
	mock.Mock
}

type mockIdentityStoreAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIdentityStoreAccountRepository) EXPECT() *mockIdentityStoreAccountRepository_Expecter {
	return &mockIdentityStoreAccountRepository_Expecter{mock: &_m.Mock}
}

// ListGroups provides a mock function with given fields: ctx, optFn
func (_m *mockIdentityStoreAccountRepository) ListGroups(ctx context.Context, optFn ...func(*types.DatabricksGroupsFilter)) <-chan repo.ChannelItem[iam.Group] {
	_va := make([]interface{}, len(optFn))
	for _i := range optFn {
		_va[_i] = optFn[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListGroups")
	}

	var r0 <-chan repo.ChannelItem[iam.Group]
	if rf, ok := ret.Get(0).(func(context.Context, ...func(*types.DatabricksGroupsFilter)) <-chan repo.ChannelItem[iam.Group]); ok {
		r0 = rf(ctx, optFn...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ChannelItem[iam.Group])
		}
	}

	return r0
}

// mockIdentityStoreAccountRepository_ListGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroups'
type mockIdentityStoreAccountRepository_ListGroups_Call struct {
	*mock.Call
}

// ListGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - optFn ...func(*types.DatabricksGroupsFilter)
func (_e *mockIdentityStoreAccountRepository_Expecter) ListGroups(ctx interface{}, optFn ...interface{}) *mockIdentityStoreAccountRepository_ListGroups_Call {
	return &mockIdentityStoreAccountRepository_ListGroups_Call{Call: _e.mock.On("ListGroups",
		append([]interface{}{ctx}, optFn...)...)}
}

func (_c *mockIdentityStoreAccountRepository_ListGroups_Call) Run(run func(ctx context.Context, optFn ...func(*types.DatabricksGroupsFilter))) *mockIdentityStoreAccountRepository_ListGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*types.DatabricksGroupsFilter), len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(func(*types.DatabricksGroupsFilter))
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *mockIdentityStoreAccountRepository_ListGroups_Call) Return(_a0 <-chan repo.ChannelItem[iam.Group]) *mockIdentityStoreAccountRepository_ListGroups_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIdentityStoreAccountRepository_ListGroups_Call) RunAndReturn(run func(context.Context, ...func(*types.DatabricksGroupsFilter)) <-chan repo.ChannelItem[iam.Group]) *mockIdentityStoreAccountRepository_ListGroups_Call {
	_c.Call.Return(run)
	return _c
}

// ListServicePrincipals provides a mock function with given fields: ctx, optFn
func (_m *mockIdentityStoreAccountRepository) ListServicePrincipals(ctx context.Context, optFn ...func(*types.DatabricksServicePrincipalFilter)) <-chan repo.ChannelItem[iam.ServicePrincipal] {
	_va := make([]interface{}, len(optFn))
	for _i := range optFn {
		_va[_i] = optFn[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListServicePrincipals")
	}

	var r0 <-chan repo.ChannelItem[iam.ServicePrincipal]
	if rf, ok := ret.Get(0).(func(context.Context, ...func(*types.DatabricksServicePrincipalFilter)) <-chan repo.ChannelItem[iam.ServicePrincipal]); ok {
		r0 = rf(ctx, optFn...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ChannelItem[iam.ServicePrincipal])
		}
	}

	return r0
}

// mockIdentityStoreAccountRepository_ListServicePrincipals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServicePrincipals'
type mockIdentityStoreAccountRepository_ListServicePrincipals_Call struct {
	*mock.Call
}

// ListServicePrincipals is a helper method to define mock.On call
//   - ctx context.Context
//   - optFn ...func(*types.DatabricksServicePrincipalFilter)
func (_e *mockIdentityStoreAccountRepository_Expecter) ListServicePrincipals(ctx interface{}, optFn ...interface{}) *mockIdentityStoreAccountRepository_ListServicePrincipals_Call {
	return &mockIdentityStoreAccountRepository_ListServicePrincipals_Call{Call: _e.mock.On("ListServicePrincipals",
		append([]interface{}{ctx}, optFn...)...)}
}

func (_c *mockIdentityStoreAccountRepository_ListServicePrincipals_Call) Run(run func(ctx context.Context, optFn ...func(*types.DatabricksServicePrincipalFilter))) *mockIdentityStoreAccountRepository_ListServicePrincipals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*types.DatabricksServicePrincipalFilter), len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(func(*types.DatabricksServicePrincipalFilter))
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *mockIdentityStoreAccountRepository_ListServicePrincipals_Call) Return(_a0 <-chan repo.ChannelItem[iam.ServicePrincipal]) *mockIdentityStoreAccountRepository_ListServicePrincipals_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIdentityStoreAccountRepository_ListServicePrincipals_Call) RunAndReturn(run func(context.Context, ...func(*types.DatabricksServicePrincipalFilter)) <-chan repo.ChannelItem[iam.ServicePrincipal]) *mockIdentityStoreAccountRepository_ListServicePrincipals_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, optFn
func (_m *mockIdentityStoreAccountRepository) ListUsers(ctx context.Context, optFn ...func(*types.DatabricksUsersFilter)) <-chan repo.ChannelItem[iam.User] {
	_va := make([]interface{}, len(optFn))
	for _i := range optFn {
		_va[_i] = optFn[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 <-chan repo.ChannelItem[iam.User]
	if rf, ok := ret.Get(0).(func(context.Context, ...func(*types.DatabricksUsersFilter)) <-chan repo.ChannelItem[iam.User]); ok {
		r0 = rf(ctx, optFn...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ChannelItem[iam.User])
		}
	}

	return r0
}

// mockIdentityStoreAccountRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type mockIdentityStoreAccountRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - optFn ...func(*types.DatabricksUsersFilter)
func (_e *mockIdentityStoreAccountRepository_Expecter) ListUsers(ctx interface{}, optFn ...interface{}) *mockIdentityStoreAccountRepository_ListUsers_Call {
	return &mockIdentityStoreAccountRepository_ListUsers_Call{Call: _e.mock.On("ListUsers",
		append([]interface{}{ctx}, optFn...)...)}
}

func (_c *mockIdentityStoreAccountRepository_ListUsers_Call) Run(run func(ctx context.Context, optFn ...func(*types.DatabricksUsersFilter))) *mockIdentityStoreAccountRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*types.DatabricksUsersFilter), len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(func(*types.DatabricksUsersFilter))
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *mockIdentityStoreAccountRepository_ListUsers_Call) Return(_a0 <-chan repo.ChannelItem[iam.User]) *mockIdentityStoreAccountRepository_ListUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIdentityStoreAccountRepository_ListUsers_Call) RunAndReturn(run func(context.Context, ...func(*types.DatabricksUsersFilter)) <-chan repo.ChannelItem[iam.User]) *mockIdentityStoreAccountRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIdentityStoreAccountRepository creates a new instance of mockIdentityStoreAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIdentityStoreAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIdentityStoreAccountRepository {
	mock := &mockIdentityStoreAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
