name: "Destroy infra"
description: "Destroy infrastructure"
inputs:
  dbClientId:
    required: true
    description: "Databricks client ID"
  dbClientSecret:
    required: true
    description: "Databricks client secret"
  dbAccountID:
    required: true
    description: "Databricks account ID"
  dbHost:
    required: true
    description: "Databricks host"
  dbMetastoreID:
    required: true
    description: "Databricks metastore ID"
  dbSqlWarehouseId:
    required: true
    description: "Databricks SQL warehouse ID"
  dbWorkspaceName:
    required: true
    description: "Databricks workspace name"
  ownerGroupName:
    required: true
    description: "Owner group name"
  target:
    required: false
    description: "Target to destroy"
    default: ""

runs:
  using: composite
  steps:
    - name: Destroy infrastructure
      shell: bash
      run: make destroy-test-infra
      env:
        TF_VAR_databricks_client_id: ${{ inputs.dbClientId }}
        TF_VAR_databricks_client_secret: ${{ inputs.dbClientSecret }}
        TF_VAR_databricks_account_id: ${{ inputs.dbAccountID }}
        TF_VAR_databricks_workspace_host: ${{ inputs.dbHost }}
        TF_VAR_databricks_metastore_id: ${{ inputs.dbMetastoreID }}
        TF_VAR_databricks_sql_warehouse_id: ${{ inputs.dbSqlWarehouseId }}
        TF_VAR_databricks_workspace_name: ${{ inputs.dbWorkspaceName }}
        TF_VAR_owner_group_name: ${{ inputs.ownerGroupName }}
        TARGET: ${{ inputs.target }}

