name: Raito CLI - Databricks Plugin - Build
on:
  push:
    branches:
      - 'main'
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  remove-old-infra:
    uses: ./.github/workflows/destroy-grants.yml
    with:
      targetEnvironment: integration_testing
      catalogs: "raito_testing"
    secrets: inherit

  setup-infra:
    uses: ./.github/workflows/generate-infra.yml
    with:
      targetEnvironment: integration_testing
      target: module.testing
    secrets: inherit

    needs:
      - remove-old-infra
    if: always()

  generate-usage:
    uses: ./.github/workflows/generate-usage.yml
    with:
      targetEnvironment: integration_testing
    secrets: inherit

    needs:
      - setup-infra
    if: needs.setup-infra.result == 'success'

  build:
    needs:
      - setup-infra
      - generate-usage
    if: needs.generate-usage.result == 'success'

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Mod Tidy
        run: go mod tidy

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.56.2

      - name: Test
        run: make test

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
